# Generated by Django 5.0.6 on 2024-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
