# Generated by Django 5.0.6 on 2024-07-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Reading", "Reading"),
                            ("Writing", "Writing"),
                            ("Drawing", "Drawing"),
                            ("Singing", "Singing"),
                            ("Dancing", "Dancing"),
                            ("Cooking", "Cooking"),
                            ("Gardening", "Gardening"),
                            ("Photography", "Photography"),
                            ("Sports", "Sports"),
                            ("Yoga", "Yoga"),
                            ("Meditation", "Meditation"),
                            (
                                "Playing Musical Instruments",
                                "Playing Musical Instruments",
                            ),
                            ("Watching Movies", "Watching Movies"),
                            ("Traveling", "Traveling"),
                            ("Volunteering", "Volunteering"),
                            ("Learning Languages", "Learning Languages"),
                            ("Coding", "Coding"),
                            ("Fashion", "Fashion"),
                            ("Painting", "Painting"),
                            ("Sculpting", "Sculpting"),
                            ("Collecting", "Collecting"),
                            ("Reading Comics", "Reading Comics"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.CharField(max_length=15, verbose_name="Age"),
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="mainapp.interest",
                verbose_name="Interests",
            ),
        ),
    ]
