# Generated by Django 5.0.6 on 2025-03-12 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_no', models.CharField(max_length=100)),
                ('gas_used', models.CharField(max_length=100)),
                ('gas_limit', models.CharField(max_length=100)),
                ('mined_on', models.DateTimeField()),
                ('block_hash', models.CharField(max_length=100)),
                ('from_address', models.CharField(max_length=100)),
                ('to_address', models.CharField(max_length=100)),
                ('tx_hash', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to='mainapp.user')),
            ],
        ),
    ]
