# Generated by Django 5.0.6 on 2025-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_blockchaintransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchaintransaction',
            name='use_case',
            field=models.CharField(choices=[('register', 'Register'), ('post', 'Post')], default='register', max_length=20),
        ),
    ]
